// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "after",
      desc: "Print everything after mask",
      input: 'line',
      output: 'line',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        return function(mask, input){
          var last, str, index;
          last = mask.indexOf('last') === 0;
          str = mask.replace(/^last /g, "");
          index = last
            ? input.lastIndexOf(str)
            : input.indexOf(str);
          if (index > -1) {
            return input.substr(index + str.length);
          } else {
            return input;
          }
        };
      }
    });
  };
}).call(this);
