// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "clipboard",
      desc: "Copy/Paste data into clipboard",
      input: 'lines',
      output: 'lines',
      enabled: false,
      doc: {
        examples: ['']
      },
      compile: function(){
        var clipboard;
        clipboard = require('clipboard');
        return function(mask, input){
          clipboard.write(input);
          return clipboard.read();
        };
      }
    });
  };
}).call(this);
