// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p, parser){
    return repo.commands.push({
      name: "col",
      desc: "Get specific columns",
      input: 'lines',
      output: 'lines',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        return function(mask, lines){
          var items, columns, ref$, pad, maxes, eachItem;
          items = p.map(function(it){
            return it.split(/[ ]+/);
          })(
          lines);
          columns = parser.numbers(mask, ((ref$ = items[0]) != null ? ref$.length : void 8) - 1);
          pad = function(str, len){
            return ((str === '' ? ' ' : str) + Array(len).join(' ')).slice(0, len);
          };
          maxes = [];
          eachItem = function(s){
            return s.forEach(function(_, i){
              var ref$;
              return maxes[i] = Math.max(s[i].length, (ref$ = maxes[i]) != null ? ref$ : 0);
            });
          };
          return p.map(function(it){
            return it.map(function(item, c){
              return pad(item, maxes[c]);
            }).filter(function(item, i){
              return columns.indexOf(i) > -1;
            }).join(' ');
          })(
          p.each(eachItem)(
          items));
        };
      }
    });
  };
}).call(this);
