// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "columns",
      desc: "Get specific column",
      input: 'lines',
      output: 'lines',
      enabled: true,
      compile: function(){
        return function(mask, lines){
          var columns, pad, maxes;
          columns = ((mask != null ? mask : "") === "" ? "0" : mask).split(',');
          pad = function(str, len){
            return ((str === '' ? ' ' : str) + Array(len).join(' ')).slice(0, len);
          };
          maxes = [];
          return p.map(function(it){
            return it.map(function(item, c){
              return pad(item, maxes[c]);
            }).filter(function(item, i){
              return columns.indexOf(i.toString()) > -1;
            }).join(' ');
          })(
          p.each(function(s){
            return s.forEach(function(_, i){
              var ref$;
              return maxes[i] = Math.max(s[i].length, (ref$ = maxes[i]) != null ? ref$ : 0);
            });
          })(
          p.map(function(it){
            return it.split(/[ ]+/);
          })(
          lines)));
        };
      }
    });
  };
}).call(this);
