// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "concat",
      desc: "Joins lines into one line",
      input: 'lines',
      output: 'line',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        return function(mask, lines){
          return p.join(mask)(
          lines);
        };
      }
    });
  };
}).call(this);
