// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "file",
      desc: "Print file content",
      input: 'line',
      output: 'lines',
      enabled: true,
      compile: function(){
        var fs;
        fs = require('fs');
        return function(mask, input, callback){
          var path, lines, res;
          path = process.cwd() + '/' + input;
          if (fs.existsSync(path) && fs.lstatSync(path).isFile()) {
            lines = fs.readFileSync(input).toString('utf8').split(/\n/);
            res = (function(){
              switch (mask) {
              case "lines":
                return lines.map(function(it){
                  return (input + ": ").yellow + it;
                });
              default:
                return lines;
              }
            }());
            return callback(res);
          } else {
            return ["file '" + path + "' not exists"];
          }
        };
      }
    });
  };
}).call(this);
