// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, common, p){
    return repo.commands.push({
      name: "find",
      desc: "Find specific line",
      input: 'multi',
      output: 'single',
      enabled: true,
      compile: function(){
        return function(mask, lines){
          return p.head(
          lines.map(common.filter(mask)).filter(function(v){
            return v !== null;
          }));
        };
      }
    });
  };
}).call(this);
