// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "ignore",
      desc: "Ignore output",
      input: 'line',
      output: 'line',
      enabled: true,
      compile: function(){
        return function(mask, line){
          return null;
        };
      }
    });
  };
}).call(this);
