// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "last",
      desc: "Get last line",
      input: 'lines',
      output: 'lines',
      enabled: true,
      compile: function(){
        return function(mask, lines){
          return p.reverse(
          p.take(mask != null ? mask : 1)(
          p.reverse(
          lines)));
        };
      }
    });
  };
}).call(this);
