// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "length",
      desc: "Calculate count of charecters",
      input: 'line',
      output: 'line',
      enabled: true,
      compile: function(){
        return {
          length: function(mask, input){
            return input.length;
          }
        };
      }
    });
  };
}).call(this);
