// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "nixar",
      desc: "Shows all commands",
      input: 'nothing',
      output: 'lines',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        return function(skip, mask, callback){
          var transform, cmd, exec;
          switch (mask != null ? mask : "") {
          case "":
            transform = function(c){
              return (c.name + " ").green + c.desc;
            };
            return callback(repo.commands.map(transform));
          case "killall":
            cmd = "killall -9 " + repo.commands.map(function(it){
              return it.name;
            }).join(" ");
            exec = require('child_process').exec;
            return exec(cmd, function(error, stdout, stderr){
              return callback(["killed"]);
            });
          default:
            return callback(repo.commands.filter(function(it){
              return it.name === mask;
            }).map(JSON.stringify));
          }
        };
      }
    });
  };
}).call(this);
