// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "remove",
      desc: "Remove substring in line",
      input: 'line',
      output: 'line',
      enabled: true,
      compile: function(){
        return function(mask, input){
          return input.split(mask).join("");
        };
      }
    });
  };
}).call(this);
