// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "replace",
      desc: "Replaces substring in line",
      input: 'line',
      output: 'line',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        return function(mask, input){
          var keys;
          keys = mask.split(',');
          return input.split(keys[0]).join(keys[1]);
        };
      }
    });
  };
}).call(this);
