// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, cat){
    return repo.commands.push({
      name: "show",
      desc: "Prints file, file lines, file created date, file modified date",
      input: 'nothing',
      output: 'lines',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: cat.compile
    });
  };
}).call(this);
