// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "sort",
      desc: "Sort lines",
      input: 'lines',
      output: 'lines',
      enabled: true,
      compile: function(){
        return function(mask, lines){
          return p.sort(
          lines);
        };
      }
    });
  };
}).call(this);
