// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "split",
      desc: "Splits line into lines",
      input: 'line',
      output: 'lines',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        return function(mask, line, callback){
          return callback(line.split(mask));
        };
      }
    });
  };
}).call(this);
