// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "split",
      desc: "Calculate minimum integer",
      input: 'line',
      output: 'lines',
      enabled: true,
      compile: function(){
        return function(mask, input, callback){
          return callback(
          input.split(mask));
        };
      }
    });
  };
}).call(this);
