// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "sum",
      desc: "Calculate sum of integers",
      input: 'lines',
      output: 'line',
      enabled: true,
      compile: function(){
        return function(mask, lines){
          return p.sum(
          lines);
        };
      }
    });
  };
}).call(this);
