// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo, p){
    return repo.commands.push({
      name: "tail",
      desc: "Remove first line",
      input: 'multi',
      output: 'multi',
      enabled: true,
      compile: function(){
        return {
          tail: function(mask, lines){
            return p.tail(
            lines);
          }
        };
      }
    });
  };
}).call(this);
