// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: "trim",
      desc: "Remove spaces from start and end of line",
      input: 'line',
      output: 'line',
      enabled: true,
      compile: function(){
        return function(mask, input){
          return String(input).replace(/^\s+|\s+$/g, '');
        };
      }
    });
  };
}).call(this);
