// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(repo){
    return repo.commands.push({
      name: 'turn',
      desc: "Calculate minimum integer",
      input: 'lines',
      output: 'line',
      enabled: true,
      doc: {
        examples: ['']
      },
      compile: function(){
        var Table;
        Table = require('easy-table');
        return function(mask, lines){
          var table, config, arr, newarr, i, j, t;
          table = /[ ]+/;
          config = (mask != null ? mask : "") === "" ? table : mask;
          arr = lines.map(function(it){
            return it.split(config);
          });
          newarr = [];
          for (i in arr) {
            for (j in arr[i]) {
              if (typeof newarr[j] === 'undefined') {
                newarr[j] = [];
              }
              newarr[j][i] = arr[i][j];
            }
          }
          t = new Table;
          switch (config) {
          case table:
            newarr.forEach(function(product){
              product.forEach(function(item, i){
                return t.cell(i, item.replace(/[ ]/g, '_'));
              });
              return t.newRow();
            });
            return t.print().trim();
          default:
            return newarr.map(function(it){
              return it.join(config);
            }).join('\n');
          }
        };
      }
    });
  };
}).call(this);
